name: infarct-seg
channels: [conda-forge, defaults]
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      - tensorflow==2.15.*
      - opencv-python